/* ============================================================================================================
   01_schema_tabelas.sql
   ------------------------------------------------------------------------------------------------------------
   Monta todas as tabelas necessárias para o projeto:
   - tabelas-base da Fórmula 1, países, cidades e aeroportos;
   - tabelas especiais do sistema: users, users_log e constructor_drivers.

   Observação de modelagem:
   - countries já possui nationality;
   - drivers e constructors já possuem country_id;
   - drivers/constructors NÃO possuem mais nationality textual.

   Este arquivo NÃO carrega dados, NÃO cria views, NÃO cria functions, NÃO cria triggers e NÃO cria índices.
   Isso deixa a organização mais clara para a entrega.
   ============================================================================================================ */

BEGIN;

/* Tabelas especiais removidas antes das tabelas-base por causa das FKs. */
DROP TABLE IF EXISTS users_log CASCADE;
DROP TABLE IF EXISTS constructor_drivers CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS constructor_standings CASCADE;
DROP TABLE IF EXISTS driver_standings CASCADE;
DROP TABLE IF EXISTS results CASCADE;
DROP TABLE IF EXISTS qualifying CASCADE;
DROP TABLE IF EXISTS races CASCADE;
DROP TABLE IF EXISTS standings CASCADE;
DROP TABLE IF EXISTS status CASCADE;
DROP TABLE IF EXISTS drivers CASCADE;
DROP TABLE IF EXISTS constructors CASCADE;
DROP TABLE IF EXISTS circuits CASCADE;
DROP TABLE IF EXISTS airports CASCADE;
DROP TABLE IF EXISTS airport_types CASCADE;
DROP TABLE IF EXISTS cities CASCADE;
DROP TABLE IF EXISTS country_languages CASCADE;
DROP TABLE IF EXISTS iso_language_codes CASCADE;
DROP TABLE IF EXISTS language_names CASCADE;
DROP TABLE IF EXISTS time_zones CASCADE;
DROP TABLE IF EXISTS countries CASCADE;
DROP TABLE IF EXISTS continents CASCADE;
DROP TABLE IF EXISTS feature_codes CASCADE;
DROP TABLE IF EXISTS seasons CASCADE;

-- Tabela seasons: guarda temporadas. Campos: id INTEGER PK; year SMALLINT UNIQUE.
CREATE TABLE seasons (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year SMALLINT NOT NULL UNIQUE
);

-- Tabela continents: guarda continentes. Campos: id INTEGER PK; code VARCHAR(10) UNIQUE; name VARCHAR(100) UNIQUE.
CREATE TABLE continents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(10) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL UNIQUE
);

-- Tabela time_zones: guarda fusos horários. Campos: id INTEGER PK; name VARCHAR(100) UNIQUE; gmt_offset/dst_offset/raw_offset NUMERIC(6,2).
CREATE TABLE time_zones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    gmt_offset NUMERIC(6, 2),
    dst_offset NUMERIC(6, 2),
    raw_offset NUMERIC(6, 2)
);

-- Tabela language_names: guarda nomes de idiomas. Campos: id INTEGER PK; name VARCHAR(100) UNIQUE.
CREATE TABLE language_names (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

-- Tabela feature_codes: guarda códigos geográficos do GeoNames. Campos: id INTEGER PK; feature_class VARCHAR(10); feature_code VARCHAR(20); name VARCHAR(255); description TEXT.
CREATE TABLE feature_codes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_class VARCHAR(10),
    feature_code VARCHAR(20),
    name VARCHAR(255),
    description TEXT
);

-- Tabela countries: guarda países e nacionalidade normalizada. Campos: id INTEGER PK; code VARCHAR(10) UNIQUE; name VARCHAR(150) UNIQUE; wikipedia_link TEXT; keywords TEXT; continent_id INTEGER FK; nationality VARCHAR(255).
CREATE TABLE countries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(10) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL UNIQUE,
    wikipedia_link TEXT,
    keywords TEXT,
    continent_id INTEGER REFERENCES continents(id),
    /* Nacionalidade passa a pertencer ao país, não diretamente a pilotos/escuderias. */
    nationality VARCHAR(255)
);

-- Tabela iso_language_codes: guarda códigos ISO de idiomas. Campos: id INTEGER PK; iso_639_3 VARCHAR(3) UNIQUE; iso_639_2 VARCHAR(20) UNIQUE; iso_639_1 VARCHAR(2) UNIQUE; language_id INTEGER FK.
CREATE TABLE iso_language_codes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iso_639_3 VARCHAR(3) UNIQUE,
    iso_639_2 VARCHAR(20) UNIQUE,
    iso_639_1 VARCHAR(2) UNIQUE,
    language_id INTEGER REFERENCES language_names(id)
);

-- Tabela country_languages: associa países a idiomas. Campos: country_id INTEGER FK; language_id INTEGER FK; PK composta.
CREATE TABLE country_languages (
    country_id INTEGER NOT NULL REFERENCES countries(id),
    language_id INTEGER NOT NULL REFERENCES language_names(id),
    PRIMARY KEY (country_id, language_id)
);

-- Tabela cities: guarda cidades e dados geográficos. Campos: id INTEGER PK; name/ascii_name VARCHAR(255); alternate_names TEXT; latitude/longitude NUMERIC(10,7); feature_code_id/country_id/time_zone_id INTEGER FK; cc/admin codes VARCHAR(20); population BIGINT; elevation/dem INTEGER; modification_date DATE.
CREATE TABLE cities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    ascii_name VARCHAR(255),
    alternate_names TEXT,
    latitude NUMERIC(10, 7),
    longitude NUMERIC(10, 7),
    feature_code_id INTEGER REFERENCES feature_codes(id),
    country_id INTEGER REFERENCES countries(id),
    time_zone_id INTEGER REFERENCES time_zones(id),
    cc2 VARCHAR(20),
    admin1_code VARCHAR(20),
    admin2_code VARCHAR(20),
    admin3_code VARCHAR(20),
    admin4_code VARCHAR(20),
    population BIGINT,
    elevation INTEGER,
    dem INTEGER,
    modification_date DATE
);

-- Tabela airport_types: guarda tipos de aeroportos. Campos: id INTEGER PK; type VARCHAR(100) UNIQUE.
CREATE TABLE airport_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(100) NOT NULL UNIQUE
);

-- Tabela airports: guarda aeroportos. Campos: id INTEGER PK; ident VARCHAR(20) UNIQUE; airport_type_id/city_id INTEGER FK; name VARCHAR(255); latitude_deg/longitude_deg NUMERIC(10,7); elevation_ft INTEGER; scheduled_service VARCHAR(10); icao/iata VARCHAR(10); gps/local VARCHAR(20); home_link/wikipedia_link/keywords TEXT.
CREATE TABLE airports (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ident VARCHAR(20) NOT NULL UNIQUE,
    airport_type_id INTEGER REFERENCES airport_types(id),
    name VARCHAR(255),
    latitude_deg NUMERIC(10, 7),
    longitude_deg NUMERIC(10, 7),
    elevation_ft INTEGER,
    city_id INTEGER REFERENCES cities(id),
    scheduled_service VARCHAR(10),
    icao_code VARCHAR(10),
    iata_code VARCHAR(10),
    gps_code VARCHAR(20),
    local_code VARCHAR(20),
    home_link TEXT,
    wikipedia_link TEXT,
    keywords TEXT
);

-- Tabela circuits: guarda circuitos de F1. Campos: id INTEGER PK; circuit_ref VARCHAR(100) UNIQUE; name VARCHAR(255); lat/long NUMERIC(10,7); city_id INTEGER FK; wikipedia_url TEXT.
CREATE TABLE circuits (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    circuit_ref VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255),
    lat NUMERIC(10, 7),
    "long" NUMERIC(10, 7),
    city_id INTEGER REFERENCES cities(id),
    wikipedia_url TEXT
);

-- Tabela constructors: guarda escuderias. Campos: id INTEGER PK; constructor_ref VARCHAR(255) UNIQUE; name VARCHAR(255) UNIQUE; country_id INTEGER FK NOT NULL; wikipedia_url TEXT.
CREATE TABLE constructors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    constructor_ref VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL UNIQUE,
    country_id INTEGER NOT NULL REFERENCES countries(id),
    wikipedia_url TEXT
);

-- Tabela drivers: guarda pilotos. Campos: id INTEGER PK; driver_ref VARCHAR(255) UNIQUE; given_name/family_name VARCHAR(255) NOT NULL; country_id INTEGER FK NOT NULL; date_of_birth DATE.
CREATE TABLE drivers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_ref VARCHAR(255) NOT NULL UNIQUE,
    given_name VARCHAR(255) NOT NULL,
    family_name VARCHAR(255) NOT NULL,
    country_id INTEGER NOT NULL REFERENCES countries(id),
    date_of_birth DATE
);

-- Tabela status: guarda status de resultados de corrida. Campos: id INTEGER PK; status VARCHAR(100) UNIQUE.
CREATE TABLE status (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(100) NOT NULL UNIQUE
);

-- Tabela standings: guarda posições, pontos e vitórias por temporada/rodada. Campos: id INTEGER PK; season_id INTEGER FK; round INTEGER; position INTEGER; points NUMERIC(10,2); wins INTEGER.
CREATE TABLE standings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id INTEGER REFERENCES seasons(id),
    round INTEGER,
    position INTEGER,
    points NUMERIC(10, 2),
    wins INTEGER
);

-- Tabela races: guarda corridas. Campos: id INTEGER PK; race_ref VARCHAR(100) UNIQUE; season_id INTEGER FK; round INTEGER; race_name VARCHAR(255); race_date DATE; race_time TIME; circuit_id INTEGER FK.
CREATE TABLE races (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race_ref VARCHAR(100) NOT NULL UNIQUE,
    season_id INTEGER REFERENCES seasons(id),
    round INTEGER,
    race_name VARCHAR(255),
    race_date DATE,
    race_time TIME,
    circuit_id INTEGER REFERENCES circuits(id)
);

-- Tabela qualifying: guarda classificação. Campos: id INTEGER PK; race_id/driver_id/constructor_id INTEGER FK; position INTEGER; q1/q2/q3 VARCHAR(20).
CREATE TABLE qualifying (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race_id INTEGER REFERENCES races(id),
    driver_id INTEGER REFERENCES drivers(id),
    constructor_id INTEGER REFERENCES constructors(id),
    position INTEGER,
    q1 VARCHAR(20),
    q2 VARCHAR(20),
    q3 VARCHAR(20)
);

-- Tabela results: guarda resultados de corrida. Campos: id INTEGER PK; race_id/driver_id/constructor_id INTEGER FK; grid INTEGER; position VARCHAR(20); position_order INTEGER; points NUMERIC(10,2); laps INTEGER; status_id INTEGER FK.
CREATE TABLE results (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race_id INTEGER REFERENCES races(id),
    driver_id INTEGER REFERENCES drivers(id),
    constructor_id INTEGER REFERENCES constructors(id),
    grid INTEGER,
    position VARCHAR(20),
    position_order INTEGER,
    points NUMERIC(10, 2),
    laps INTEGER,
    status_id INTEGER REFERENCES status(id)
);

-- Tabela driver_standings: liga standings a pilotos. Campos: standing_id INTEGER FK; driver_id INTEGER FK; PK composta.
CREATE TABLE driver_standings (
    standing_id INTEGER NOT NULL REFERENCES standings(id),
    driver_id INTEGER NOT NULL REFERENCES drivers(id),
    PRIMARY KEY (standing_id, driver_id)
);

-- Tabela constructor_standings: liga standings a escuderias. Campos: standing_id INTEGER FK; constructor_id INTEGER FK; PK composta.
CREATE TABLE constructor_standings (
    standing_id INTEGER NOT NULL REFERENCES standings(id),
    constructor_id INTEGER NOT NULL REFERENCES constructors(id),
    PRIMARY KEY (standing_id, constructor_id)
);

/* ============================================================================================================
   TABELAS ESPECIAIS DO SISTEMA
   ------------------------------------------------------------------------------------------------------------
   USERS e USERS_LOG foram adicionadas para login e auditoria de acesso.
   constructor_drivers é uma associação auxiliar opcional para registrar pilotos inseridos por arquivo por uma
   escuderia logada. O histórico real de pilotos que correram por escuderia continua sendo obtido por RESULTS.
   ============================================================================================================ */
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Tabela especial users: guarda usuários do sistema. Campos: userid INTEGER PK; login VARCHAR(150) UNIQUE; password TEXT; tipo VARCHAR(20); id_original INTEGER; created_at/updated_at TIMESTAMP; CHECK de vínculo por tipo.
CREATE TABLE users (
    userid       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login        VARCHAR(150) NOT NULL UNIQUE,
    password     TEXT NOT NULL,
    tipo         VARCHAR(20) NOT NULL CHECK (tipo IN ('Admin', 'Escuderia', 'Piloto')),
    id_original  INTEGER,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_users_id_original_por_tipo CHECK (
        (tipo = 'Admin' AND id_original IS NULL)
        OR
        (tipo IN ('Escuderia', 'Piloto') AND id_original IS NOT NULL)
    )
);

-- Tabela especial users_log: guarda login/logout para auditoria. Campos: id INTEGER PK; userid INTEGER FK; action_type VARCHAR(20); action_timestamp TIMESTAMP.
CREATE TABLE users_log (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userid           INTEGER NOT NULL REFERENCES users(userid),
    action_type      VARCHAR(20) NOT NULL CHECK (action_type IN ('LOGIN', 'LOGOUT')),
    action_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Tabela especial constructor_drivers: registra pilotos criados por escuderia via sistema. Campos: constructor_id INTEGER FK; driver_id INTEGER FK; registered_at TIMESTAMP; PK composta.
CREATE TABLE constructor_drivers (
    constructor_id INTEGER NOT NULL REFERENCES constructors(id),
    driver_id      INTEGER NOT NULL REFERENCES drivers(id),
    registered_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (constructor_id, driver_id)
);

COMMIT;
